---
title: "Math 183 Final Project Code (Opioid Crisis & SIS)"
author: "Grace Zhao, Zoe Piccirillo, Sam Ford, Mira Terdiman"
date: "2023-12-15"
output: pdf_document
---

**General Model Code**
We used this code to fit out parameters and examine baseline behavior. To model our SARD model, we set U=0.
```{r}
library(deSolve)
library(phaseR)
library(pracma)
library(writexl)

#these parameters maintain a slight growth in S, 
#2% of Susceptible are Abusers
#The recovery population is 1/2 the Abuser population

b = 0.0000000012 # interaction term between susceptible and abuse
c = 0.3775 # from abuse to recovery
d = 0.008 # death of abusers/misusers
e = 0.75 #relapse
g = 0.4 #from SIS abuse to recovery (assuming people at SIS recover slightly more than general abusers)
l = 3  #adjusting this parameter would adjust willingness to use an SIS and determine how quickly U reaches carrying capacity
k = 6000 #adjusting this parameter changes the SIS carrying capacity

#Assumptions for LA County Population: 
#S0: 9,830,000 (2021 LA County Population) 
#A0: 196,600 (estimate that 2% of adults abuse opioids)
#There are, on average 1,570 fatal overdoses per year (without SIS)
#Assume at time t=0, 100 people use SIS

state <- c(S = 9535000, A = 196500, R = 98300, D = 0, U = 100) #to model SARD, let U=0
parameters <- c(b,c,d,e,g,l,k)

N = 9830000

pre_op <- function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    dS <- -(b*A)*(S) - b*S*(A+U/2) + (0.00055*N) 
    dA <- b*S*(A+U/2) - (c+d)*A + e*R + (b*A)*S - 0.0118*A - l*U*(1-(U/k)) 
    dR <- c*A - e*R - 0.00372*R + g*U 
    dD <- d*A
    dU <- l*U*(1-(U/k)) - g*U 
    list(c(dS,dA,dR,dD, dU))
  })
}

times <- seq(0,30, 0.001)

Y <- ode(y = state, times = times, func = pre_op, parms = parameters)
head(Y) 
tail(Y)

par(oma = c(0, 0, 3, 0))
plot(Y, xlab = "time", ylab = "-", xlim=c(0,30))
mtext(outer = TRUE, side = 3, "Opioid Model", cex = 1.5)
```

Analysis of SIS recovery rate (g/theta)
```{r}
library(deSolve)
library(phaseR)
library(pracma)

#these parameters maintain a slight growth in S, 
#2% of Susceptible are Abusers
#The recovery population is 1/2 the Abuser population
a = 0.00023586
b = 0.0000000012 # interaction term between susceptible and abuse
c = 0.3775 # from abuse to recovery
d = 0.008 # death of abusers/misusers
e = 0.75 #relapse
g = 0.8 #from SIS abuse to recovery (assuming people at SIS recover slightly more than general abusers)
l = 3  #adjusting this parameter would adjust willingness to use an SIS and determine how quickly U reaches carrying capacity
k = 6000 #adjusting this parameter changes the SIS carrying capacity

##Assumptions for LA County Population: 
#S0: 9,830,000 (2021 LA County Population) #find adult population? 
#A0: 196,600 (estimate that 2% of adults abuse opioids)
#parameter fitting: find parameters such that given S0 and A0, there are D1 deaths 
#There are, on average 1,570 fatal overdoses per year (without SIS)
#Assume at time t=0, 100 people use SIS

state <- c(S = 9535000, A = 196500, R = 98300, D = 0, U = 100)
parameters <- c(a,b,c,d,e,g,l,k)

N = 9830000

pre_op <- function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    dS <- -a*(S) - b*S*(A+U/2) + (0.00055*N) #added a natural replacement rate for better long-term outcomes
    dA <- b*S*(A+U/2) - (c+d)*A + e*R + a*S - 0.0118*A - l*U*(1-(U/k)) 
    dR <- c*A - e*R - 0.00372*R + g*U 
    dD <- d*A
    dU <- l*U*(1-(U/k)) - g*U 
    list(c(dS,dA,dR,dD, dU))
  })
}

times <- seq(0,30, 0.001)

Y <- ode(y = state, times = times, func = pre_op, parms = parameters)
head(Y) 
tail(Y)

par(oma = c(0, 0, 3, 0))
plot(Y, xlab = "time", ylab = "-", xlim=c(0,30))
mtext(outer = TRUE, side = 3, "Opioid Model", cex = 1.5)


run_op <- function(g){
  parameters["g"] <- g
  ode(y = state, times = times, func = pre_op, parms = parameters)
}

#defining different scenarios for l
g <- c(0.4, 0.8, 1.6, 3.2, 6.2) #this says that we will go through 5 different scenarios: l = 1*1, l=1*2, ..., l=1*5

#run and plot default scenario (here it is set to l = 1, we could change this)

run0 <- run_op(g = g[1])
plot(run0)

#run other 4 scenarios of l values, where [-1] means all except the first

runs <- lapply(g[-1], run_op)
plot(run0, runs, las=1)
legend("bottomright", legend = paste("g = ", g), lty=1:5, col = 1:5)

#this should plot 5 scenarios on each of our 5 state plots!
```


Analysis of Relapse Rates
```{r}
#code is very similar, but we define the final ode a bit differently in order to have it run multiple times while changing one parameter
#in this example, I am changing the "l" parameter, which relates to willingness to go to an SIS

a = 0.0002359
b = 0.0000000012 
c = 0.3775 
d = 0.008 
e = 0.75
g = 0.4 
l = 3
k = 6000

pre_op <- function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    dS <- -a*(S) - b*S*(A+U/2) + (0.00055*N) 
    dA <- b*S*(A+U/2) - (c+d)*A + e*R + (b*A)*S - 0.0118*A - l*U*(1-(U/k)) 
    dR <- c*A - e*R - 0.00372*R + g*U 
    dD <- d*A
    dU <- l*U*(1-(U/k)) - g*U 
    list(c(dS,dA,dR,dD, dU))
  })
}

parameters <- c(a,b,c,d,e,g,l,k)
state <- c(S = 9535000, A = 196500, R = 98300, D = 0, U = 100)
times <- seq(0,30, 0.001)

run_op <- function(e){
  parameters["e"] <- e
  ode(y = state, times = times, func = pre_op, parms = parameters)
}

#defining different scenarios for l
e <- c(.75, .14, .4, .6) #this says that we will go through 5 different scenarios: l = 1*1, l=1*2, ..., l=1*5

#run and plot default scenario (here it is set to l = 1, we could change this)

run0 <- run_op(e = e[1])
plot(run0)
#run other 4 scenarios of l values, where [-1] means all except the first

runs <- lapply(e[-1], run_op)
plot(run0, runs, las=1)
legend("bottomright", legend = paste("e = ", e), lty=1:5, col = 1:5)

#this should plot 5 scenarios on each of our 5 state plots!
```
